name: paper_app
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy==1.26.4
  - pandas==2.2.1
  - matplotlib
  - seaborn
  - plotly==5.19.0
  - scikit-learn==1.3.0
  - xgboost==2.0.3
  - jupyterlab
  - pip
  - pip:
      - pytimetk
      - openai==1.23.6
      - langchain==0.1.16
      - langchain_openai==0.1.3
      - langchain-experimental==0.0.57
      - langchain-community==0.0.34
      - streamlit==1.33.0
      - pypdf==4.2.0
      - PyYAML==6.0.1
      - chromadb==0.5.0
      - watchdog
      - h2o==3.46.0.1
      - sqlalchemy==2.0.29



